// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PL9lSkOmNCDI2rQXumPVu3E0Ihcai1g',
    appId: '1:633401574228:web:e6125f366d0fd85abe7ec1',
    messagingSenderId: '633401574228',
    projectId: 'test-flutter-push-notification',
    authDomain: 'test-flutter-push-notification.firebaseapp.com',
    storageBucket: 'test-flutter-push-notification.appspot.com',
    measurementId: 'G-4LCMNL0F81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfEyh8ZIhOCuqBJxE8eylyGC60z6cBX6A',
    appId: '1:633401574228:android:589e9fbeaf9d6b49be7ec1',
    messagingSenderId: '633401574228',
    projectId: 'test-flutter-push-notification',
    storageBucket: 'test-flutter-push-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRG1TqWWUkpynT9vAaJlcFDnVZfWi8KK8',
    appId: '1:633401574228:ios:be6b35779d67cfb0be7ec1',
    messagingSenderId: '633401574228',
    projectId: 'test-flutter-push-notification',
    storageBucket: 'test-flutter-push-notification.appspot.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRG1TqWWUkpynT9vAaJlcFDnVZfWi8KK8',
    appId: '1:633401574228:ios:bf46d964d3d52393be7ec1',
    messagingSenderId: '633401574228',
    projectId: 'test-flutter-push-notification',
    storageBucket: 'test-flutter-push-notification.appspot.com',
    iosBundleId: 'com.example.flutterPushNotification.RunnerTests',
  );
}
